### ISSUE TITLE
Labs Avatar not being shown?

### ISSUE THREAD

**Issue by TheBeachLab** [fablabbcn/fablabs.io#86]
I have seen this issue in a couple of computers now. Some labs have a missing Avatar icon and showing as if it was a broken link. I think there might be a problem somewhere.

**Comment by lespacedunmatin** [comment]
@TheBeachLab : do you have an example ?

**Comment by TheBeachLab** [comment]
Mmmm somehow it is fixed now. I checked it in various computers even from India and last week and it was showing this issue.

**Comment by hiromipaw** [comment]
Hi guys, I fixed this issue last week. It was a problem with our image processing service. Thanks for reporting it.

**Comment by openp2pdesign** [comment]
Still happening... See for example [Otafab](https://www.fablabs.io/otafab) which was just approved

![screen shot 2016-10-28 at 10 22 02](https://cloud.githubusercontent.com/assets/1458229/19799732/76a44a5e-9cf8-11e6-99d5-9e3ce1aeded9.png)

**Comment by openp2pdesign** [comment]
And also for some links as well [(example: Fab Lab Barcelona)](https://www.fablabs.io/fablabbcn)

![screen shot 2016-11-02 at 17 28 57](https://cloud.githubusercontent.com/assets/1458229/19937540/fe85882a-a121-11e6-9024-5749e340929e.png)

**Comment by openp2pdesign** [comment]
Still happening:
- https://www.fablabs.io/projects/design-aluminium
- https://www.fablabs.io/labs/fablabreunion

<img width="1125" alt="screen shot 2018-06-14 at 09 56 09" src="https://user-images.githubusercontent.com/1458229/41398939-465de1bc-6fb9-11e8-94d3-bec51233fcbf.png">

**Comment by vierarb** [comment]
Any other place the images are not being shown?
